brusnika_project/restraunt_menu/api/urls.py
from django.urls import path

from restraunt_menu.api.views import MenuAPIView


app_name = 'api'

urlpatterns = [
    path('', MenuAPIView.as_view(), name='menu_items')
]

brusnika_project/restraunt_menu/app/urls.py
from django.urls import path, include, re_path
from restraunt_menu.app.views import ListView, OrderView


app_name = 'app'

urlpatterns = [
    path('', ListView.as_view(), name='list'),
    path('bill/', OrderView.as_view(), name='bill')
]

brusnika_project/urls.py
from django.contrib import admin
from django.urls import path, include

from restraunt_menu.app import urls as app_urls
from restraunt_menu.api import urls as api_urls


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(app_urls)),
    path('api/', include(api_urls)),
]

brusnika_project/restraunt_menu/models.py
from django.db import models


class Category(models.Model):
    title = models.CharField(max_length=200, unique=True)

    class Meta:
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'

    def __str__(self):
        return self.title


class MenuItem(models.Model):
    title = models.CharField(null=True, max_length=100, unique=True)
    calories = models.PositiveIntegerField()
    price = models.PositiveIntegerField()
    image = models.ImageField(upload_to='static/media/images/', null=True, blank=True)
    allergens = models.ManyToManyField(
        'Allergens',
        related_name='menu_items',
    )
    category = models.ForeignKey(
        'Category',
        related_name='menu_items',
        on_delete=models.CASCADE,
    )

    class Meta:
        verbose_name = 'Menu item'
        verbose_name_plural = 'Menu items'
        order_with_respect_to = 'title'

    def __str__(self):
        return self.title


class Allergens(models.Model):
    title = models.CharField('Allergens', max_length=100)

    class Meta:
        verbose_name = 'Allergen'
        verbose_name_plural = 'Allergens'
        order_with_respect_to = 'title'

    def __str__(self):
        return self.title

brusnika_project/restraunt_menu/api/views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import ListCreateAPIView
from rest_framework.authentication import SessionAuthentication

from restraunt_menu.models import MenuItem
from restraunt_menu.api.serializers import MenuItemSerializer


class MenuAPIView(ListCreateAPIView):
    serializer_class = MenuItemSerializer
    authentication_classes = [SessionAuthentication]

    def post(self, request, *args, **kwargs):
        serializer = self.serializer_class(data=request.data)
        if serializer.is_valid():
            serializer.save()
            return Response(serializer.data, status=status.HTTP_201_CREATED)
        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

brusnika_project/restraunt_menu/app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from restraunt_menu.models import MenuItem, Allergens, Category


class ListView(TemplateView):
    template_name = 'restraunt_menu/list.html'

    def get(self, request, *args, **kwargs):
        context = {'categories': Category.objects.all()}
        return render(request, self.template_name, context)


class OrderView(TemplateView):
    template_name = 'restraunt_menu/bill.html'

    def get_context_data(self, menu_item_ids, *args, **kwargs):
        context = super().get_context_data(*args, **kwargs)
        menu_items = MenuItem.objects.filter(id__in=menu_item_ids)
        menu_item_titles = menu_items.values_list('title', flat=True)
        menu_items_data = menu_items.values_list('title', 'price')
        context = {
            'titles': menu_item_titles,
            'order': [],
            'total': 0,
        }
        for title, price in menu_items_data:
            context['order'].append((price, Allergens.objects.filter(menu_items__title=title)))
            context['total'] += price

        return context

    def post(self, request, *args, **kwargs):
        order = request.POST.getlist('ordered')
        menu_item_ids = [int(item_id) for item_id in order]
        context = self.get_context_data(menu_item_ids)

        return render(request, self.template_name, context)

brusnika_project/restraunt_menu/views/api_views.py
from rest_framework.response import Response
from rest_framework import status
from rest_framework.generics import ListCreateAPIView

from ..models import MenuItem
from ..serializers import MenuItemSerializer


class MenuAPIView(ListCreateAPIView):
    queryset = MenuItem.items.all()
    serializer_class = MenuItemSerializer

    def get(self, request):
        serializer = self.serializer_class(self.get_queryset(), many=True)

        return Response(serializer.data)

    def post(self, request, format=None):
        serializer = self.serializer_class(data=request.data)

        if serializer.is_valid():
            serializer.save()

            return Response(serializer.data, status=status.HTTP_201_CREATED)

        return Response(serializer.errors, status=status.HTTP_400_BAD_REQUEST)

brusnika_project/restraunt_menu/templates/restraunt_menu/bill.html
<!DOCTYPE html>
<html>
    <head>
        <title>Bill</title>
        <link href="/static/css/bill.css" type="text/css" rel="stylesheet" />
        <meta charset="utf-8">
    </head>
    <body>        
        <table>
            <thead>
                <tr>
                    <th class="column" colspan="{{ titles.count }}">
                        <h2>Your order:</h2>
                    </th>
                </tr>
                <tr>
                    {% for title in titles %}
                        <th class="column">{{ title }}</th>
                    {% endfor %}
                </tr>
            </thead>
            <tbody>
                <tr>
                    {% for price, allergens in order %}
                        <td class="column">
                            <span class="price">Price: {{ price }}</span>
                            <span class="allergens">Allergens:</span>
                            <span class="list">
                                {% for allergen in allergens %}
                                    <li>{{ allergen }}</li>
                                {% endfor %}
                            </span>
                        </td>
                    {% endfor %}
                </tr>
            </tbody>
            <tfoot>
                <tr>
                    <th class="column" colspan="{{ titles.count }}">
                        <h2 class="total">Total price: {{ total }}</h2>
                    </th>
                </tr>
            </tfoot>
        </table>
    </body>
</html>

brusnika_project/restraunt_menu/templates/restraunt_menu/list.html
<!DOCTYPE html>
<html>
    <head>
        <title>Menu</title>
        <link href="/static/css/list.css" type="text/css" rel="stylesheet" />
        <meta charset="utf-8">
    </head>
    <body>
        <form action="{% url "app:bill" %}" method="POST">
            {% csrf_token %}
            {% for category in categories %}
                <div class="category">
                    <h2>{{ category }}</h2>
                    <ul>
                        {% for item in category.menu_items.all %}
                            <li class="category">
                                {% with pk=item.pk %}
                                    <input class="ordered" id="{{ pk }}" type="checkbox" name="ordered" value="{{ pk }}">
                                    <label for="{{ pk }}">{{ item.title }}</label>
                                {% endwith %}
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            {% endfor %}
            <input id="btn" type="submit" value="Submit"><br>
        </form>
    </body>
</html>